nama = input("Masukkan nama anda: ")
nomor = input("Masukkan NIM anda: ")

print("Hai, " + nama + "! Selamat datang!")
print("NIM anda adalah " + nomor + "!")

print("Pertanyaan 1")
print("Diketahui sisi = 6, sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = int(input("Sisi : "))
n2 = int(input("sisi : "))
print("Bengun datar tersebut adalah", nb, "dan luasnya adalah", n1*n2)

print("Pertanyaan 2")
print("Diketahui alas = 7, tinggi = 8, sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = int(input("Alas : "))
n2 = int(input("Tinggi : "))
print("Bangun datar tersebut adalah", nb, "dan luasnya adalah", n1*n2/2)

print("Pertanyaan 3")
print("Diketahui panjang = 4, lebar = 9, sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = int(input("Panjang : "))
n2 = int(input("Lebar : "))
print("Bangun datar tersebut adalah", nb, "dan luasnya adalah", n1*n2)

print("Pertanyaan 4")
print("Diketahui jari-jari = 56, sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = float(input("Phi (π)  : "))
n2 = int(input("Jari-jari (r) : "))
print("Bangun datar tersebut adalah", nb, "dan luasnya adalah", n1*n2*n2)

print("Pertanyaan 5")
print("Diketahui diagonal 1 = 4, diagonal 2 = 8 sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = int(input("Diagonal 1 : "))
n2 = int(input("Diagonal 2 : "))
print("Bangun datar tersebut adalah", nb, "dan luasnya adalah", 0.5*n1*n2)

print("Pertanyaaan 6")
print("Pertanyaan 7")
print("Diketahui alas = 9, tinggi = 7, sebutkan nama dan hitunglah luas bangun datar tersebut!")
nb = input("Nama bangun datar : ")
n1 = int(input("Alas: "))
n2 = int(input("Tinggi: "))
print("Bangun datar tersebut adalah", nb, "dan luasnya adalah", n1*n2)
